name: Build iOS
description: Build iOS
runs:
  using: composite
  steps:

    - name: Parse Flutter version
      uses: kuhnroyal/flutter-fvm-config-action@v1

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}
        cache: true
    
    - name: Download Flutter packages
      shell: bash
      run: flutter pub get

    - name: Import Provisioning Profile
      shell: bash
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo -n ${{ secrets.PROVISIONING_PROFILE_DATA }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/${{ env.PROVISIONING_PROFILE_NAME }}

    - name: Import Code-Signing Certificates
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.APPLE_CERTIFICATES_P12 }}
        p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

    - name: Create ipa file
      shell: bash
      run: |
        flutter build ipa \
          --export-options-plist=${{ env.EXPORT_OPTIONS_NAME }} \
          --release \
          --build-number ${{ github.run_number }}
