name: Build Android
description: Build Android

inputs:
  android_keystore:
    description: 'key.jksを上書きするファイル'
    required: true
  android_properties:
    description: 'key.propertiesを上書きするファイル'
    required: true

runs:
  using: composite
  steps:

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # リリースビルドに必要なキーストアのセットアップ
    - name: Setup Release Keystore
      shell: bash
      run: |
        echo "${{ inputs.android_keystore }}" | base64 --decode > android/app/key.jks
        echo "${{ inputs.android_properties }}" | base64 --decode > android/key.properties

    # ビルド
    - name: Build
      shell: bash
      run: |
        flutter build appbundle \
          --release \
          --build-number ${{ github.run_number }}
