name: Deploy Android to App Distribution

on:
  workflow_dispatch:

jobs:
  build_ios:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out my repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Build Android
        uses: ./.github/actions/build-android
        with:
          android_keystore: ${{ secrets.ANDROID_KEYSTORE }}
          android_properties: ${{ secrets.ANDROID_PROPERTIES }}

      # Firebase App Distribution にアップロード
      - name: Upload To Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: developer
          file: build/app/outputs/flutter-apk/app-release.apk
  